# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample App Customers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample App Customers
  pod 'OptimizelySDKiOS', '0.4.0-alpha2'

end
