# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobile Buy SDK Advanced Sample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Mobile Buy SDK Advanced Sample
  pod 'OptimizelySDKiOS', '=0.4.0-alpha2'
end
