#!/usr/bin/env ruby

# Generates new schema typed swift code for the ios mobile buy SDK; and updates the
# version of the storefront API being used by the SDK
#
# build.rb

require 'bundler/setup'
require 'net/http'
require 'json'
require 'optparse'
require 'graphql_schema'
require 'graphql_swift_gen'
require 'fileutils'
require 'erb'
require 'xcodeproj'

shared_storefront_api_key = "4a6c829ec3cb12ef9004bf8ed27adf12"
storefront_api_version = ARGV[0]
generated_nesting_class = 'Storefront'

endpoint = URI("https://app.shopify.com/services/graphql/introspection/storefront?api_client_api_key=#{shared_storefront_api_key}&api_version=#{storefront_api_version}")
scripts_path = __dir__
parent_path = File.expand_path('..', scripts_path)
generated_code_path = File.join(parent_path, 'Buy', 'Generated')

res = Net::HTTP.get_response(endpoint)

if res.is_a?(Net::HTTPSuccess)
  puts "Using Storefront API version: #{storefront_api_version}"

  template_path = File.join(scripts_path, 'version.swift.erb')
  output = ERB.new(File.read(template_path)).result()
  output_path = File.join(generated_code_path, 'Storefront.Schema.swift')

  File.open(output_path, "w") { |f|
  	f.write "#{output}"
  }
  schema = GraphQLSchema.new(JSON.parse(res.body))
else
  puts "Invalid API version provided. Please try again."
	exit(false)
end

customScalars = [
	GraphQLSwiftGen::Scalar.new(
	  type_name:       'DateTime',
	  swift_type:      'Date',
	  deserialize_expr: ->(expr) { "GraphQL.iso8601DateParser.date(from: #{expr})!"  },
	  serialize_expr:   ->(expr) { "GraphQL.iso8601DateParser.string(from: #{expr})" },
	),
	GraphQLSwiftGen::Scalar.new(
      type_name:       'URL',
      swift_type:      'URL',
      deserialize_expr: ->(expr) { "URL(string: #{expr})!" },
      serialize_expr:   ->(expr) { "#{expr}.absoluteString" },
    ),
	GraphQLSwiftGen::Scalar.new(
	  type_name:       'Int32',
	  swift_type:      'Int',
	  deserialize_expr: ->(expr) { "Int(#{expr})"   },
	  serialize_expr:   ->(expr) { "Int32(#{expr})" },
	),
	GraphQLSwiftGen::Scalar.new(
	  type_name:       'Money',
	  swift_type:      'Decimal',
	  deserialize_expr: ->(expr) { "Decimal(string: #{expr}, locale: GraphQL.posixLocale)" },
	  serialize_expr:   ->(expr) { "String(describing: #{expr})"                           },
	),
	GraphQLSwiftGen::Scalar.new(
	  type_name:       'Decimal',
	  swift_type:      'Decimal',
	  deserialize_expr: ->(expr) { "Decimal(string: #{expr}, locale: GraphQL.posixLocale)" },
	  serialize_expr:   ->(expr) { "String(describing: #{expr})"                           },
	)
]

content = GraphQLSwiftGen.new(
	schema,
	nest_under: generated_nesting_class,
	import_graphql_support: false,
	custom_scalars: customScalars
)
content.save(generated_code_path)


################################################
# Add newly generated sources to xcode project
################################################

project_path = File.join(parent_path, 'Buy.xcodeproj')
project = Xcodeproj::Project.open(project_path)

generated_files = Dir[File.join(generated_code_path, generated_nesting_class, '*')]

buy_target = project.targets.find{ |t| t.name == 'Buy'}
source_files = buy_target.source_build_phase.files.to_a.map do |pbx_build_file|
	pbx_build_file.file_ref.real_path.to_s
end

generated_files.each{ |f|
  unless source_files.include?(f)
    new_file = project.new_file(f)
    buy_target.source_build_phase.add_file_reference(new_file, true)
    new_files << new_file
  end
}

project.save
