#!/usr/bin/env ruby

parent_path = File.expand_path('..', __dir__)
file_path = File.join(parent_path, 'Buy', 'Utilities', 'SDK.swift')
src = File.read(file_path)
if !src
    puts "Could not read file."
    exit(false)
end

version = src.match(/static let version = "([0-9.]+)"/i).captures[0]

components = version.split('.')
components[1] = components[1].to_i + 1
new_version = components.join('.')

new_src = src.gsub(/static let version = "([0-9.]+)"/, "static let version = \"#{new_version}\"")
File.open(file_path, "w") { |file| 
    file.puts new_src
}

podspec_path = File.join(parent_path, 'Mobile-Buy-SDK.podspec')
unless File.exist?(podspec_path) && File.writable?(podspec_path)
    raise "unable to open #{podspec_path}"
end

podspec_src = File.read(podspec_path)
if match = podspec_src.match(/s.version\s*= '([0-9.]+)'/i)
    current = match.captures[0]
    new_def = match.to_s.gsub(current, new_version)
    podspec_src.gsub!(match.to_s, new_def)
end

File.open(podspec_path, 'w') do |podspec|
    podspec.puts podspec_src
end

puts new_version
