#!/usr/bin/env ruby

require 'bundler/setup'
require 'net/http'
require 'json'
require 'optparse'
require 'graphql_schema'
require 'graphql_swift_gen'

endpoint = URI("https://app.shopify.com/services/ping/storefront_graphql_schema")
body     = Net::HTTP.get(endpoint)
schema   = GraphQLSchema.new(JSON.parse(body))

customScalars = [
	GraphQLSwiftGen::Scalar.new(
	  type_name:       'DateTime',
	  swift_type:      'Date',
	  deserialize_expr: ->(expr) { "GraphQL.iso8601DateParser.date(from: #{expr})!"  },
	  serialize_expr:   ->(expr) { "GraphQL.iso8601DateParser.string(from: #{expr})" },
	),
	GraphQLSwiftGen::Scalar.new(
	  type_name:       'Money',
	  swift_type:      'NSDecimalNumber',
	  deserialize_expr: ->(expr) { "NSDecimalNumber(string: #{expr}, locale: GraphQL.posixLocale)" },
	  serialize_expr:   ->(expr) { "#{expr}.description(withLocale: GraphQL.posixLocale)"          },
	)
]

content = GraphQLSwiftGen.new(
	schema, 
	nest_under: 'Storefront', 
	import_graphql_support: false, 
	custom_scalars: customScalars
)
content.save("../Buy/Generated/")
