//
//  BUYImageKit.h
//  Mobile Buy SDK
//
//  Created by Rune Madsen on 2015-07-17.
//  Copyright (c) 2015 Shopify. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BUYImageKit : NSObject

// Drawing Methods
+ (void)drawVariantCloseImageWithFrame: (CGRect)frame;
+ (void)drawPreviousSelectionIndicatorImageWithFrame: (CGRect)frame;
+ (void)drawDisclosureIndicatorImageWithFrame: (CGRect)frame;
+ (void)drawProductViewCloseImageWithFrame: (CGRect)frame;
+ (void)drawProductViewBackImageWithFrame: (CGRect)frame;
+ (void)drawVariantBackImageWithFrame: (CGRect)frame;

// Generated Images
+ (UIImage*)imageOfVariantCloseImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPreviousSelectionIndicatorImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfDisclosureIndicatorImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfProductViewCloseImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfProductViewBackImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfVariantBackImageWithFrame: (CGRect)frame;

@end
