//
//  BUYImageKit.h
//  Mobile Buy SDK
//
//  Created by Rune Madsen on 2015-08-04.
//  Copyright (c) 2015 Shopify. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

@import Foundation;
@import UIKit;

@interface BUYImageKit : NSObject

// Generated Images
+ (UIImage*)imageOfVariantCloseImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfPreviousSelectionIndicatorImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfDisclosureIndicatorImageWithFrame: (CGRect)frame color:(UIColor*)color;
+ (UIImage*)imageOfProductViewCloseImageWithFrame: (CGRect)frame color:(UIColor*)color hasShadow:(BOOL)hasShadow;
+ (UIImage*)imageOfProductViewBackImageWithFrame: (CGRect)frame;
+ (UIImage*)imageOfVariantBackImageWithFrame: (CGRect)frame;

@end
