name: Ensure Mobile-Buy-SDK version is bumped

on:
  push:
    branches:
      - release/**
jobs:
  build:
    runs-on: macOS-latest
      
    steps:
    - uses: actions/checkout@master

    - name: Ensure Mobile-Buy-SDK.podspec version is changed
      run: |
        LINES=$(git diff master..HEAD -- Mobile-Buy-SDK.podspec | grep s.version | wc -l)
        if [ "$LINES" -eq "2" ]; then
          echo "Podfile version was updated";
          exit 0;
        else 
          echo "::error::Mobile-Buy-SDK.podspec must be updated with new version"
          exit 1;
        fi
